// This function prompts the user for permission to use the microphone and returns a Promise
export function getMicrophoneAccess() {
    const constraints = { audio: true, video: false }; // We only want audio
    // Return the Promise generated by getUserMedia directly
    return navigator.mediaDevices.getUserMedia(constraints);
  }
  